# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60f33c4e8adfbbdf187ecd3ebdcbfc989585fc690c46ceac4b214875600adb6758e28ada34c58527d562d3a8226e1452a12ddf906c91b1c12e5a4456d2b563bf

test:
  secret_key_base: ec16048bbd8f9b56242d9ce2813c9101799f28499dda6c5fc7864ebcc3e854f5f4f0c896103e14e477d0d20e8d1c3f98ca09c75006bb5fd2057177ce1aee5cb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
